server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 30
    prefer-ip-address: "true"
    hostname: localhost
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default: 
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
springdoc:
  api-docs:
    path: book-service/v3/api-docs
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/cambio_service?useSSL=false&enabledTLSProtocols=TLSv1.2&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3310/cambio_service?useSSL=false&enabledTLSProtocols=TLSv1.2&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    schemas: book_service
    user: root
    password: 123456      
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
        - prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true
  
    